// Code generated by gen.go; DO NOT EDIT.
package postgresql

// IsKeyword reports whether the name is a PostgreSQL reserved keyword.
func IsKeyword(name string) bool {
	switch len(name) {
	case 2:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 's', 'S':
				return true // as
			}
		case 'd', 'D':
			switch name[1] {
			case 'o', 'O':
				return true // do
			}
		case 'i', 'I':
			switch name[1] {
			case 'n', 'N':
				return true // in
			case 's', 'S':
				return true // is
			}
		case 'o', 'O':
			switch name[1] {
			case 'n', 'N':
				return true // on
			case 'r', 'R':
				return true // or
			}
		case 't', 'T':
			switch name[1] {
			case 'o', 'O':
				return true // to
			}
		}
	case 3:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 'l', 'L':
				switch name[2] {
				case 'l', 'L':
					return true // all
				}
			case 'n', 'N':
				switch name[2] {
				case 'd', 'D':
					return true // and
				case 'y', 'Y':
					return true // any
				}
			case 's', 'S':
				switch name[2] {
				case 'c', 'C':
					return true // asc
				}
			}
		case 'e', 'E':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'd', 'D':
					return true // end
				}
			}
		case 'f', 'F':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'r', 'R':
					return true // for
				}
			}
		case 'n', 'N':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'w', 'W':
					return true // new
				}
			case 'o', 'O':
				switch name[2] {
				case 't', 'T':
					return true // not
				}
			}
		case 'o', 'O':
			switch name[1] {
			case 'l', 'L':
				switch name[2] {
				case 'd', 'D':
					return true // old
				}
			}
		}
	case 4:
		switch name[0] {
		case 'b', 'B':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'h', 'H':
						return true // both
					}
				}
			}
		case 'c', 'C':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 's', 'S':
					switch name[3] {
					case 'e', 'E':
						return true // case
					case 't', 'T':
						return true // cast
					}
				}
			}
		case 'd', 'D':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 's', 'S':
					switch name[3] {
					case 'c', 'C':
						return true // desc
					}
				}
			}
		case 'e', 'E':
			switch name[1] {
			case 'l', 'L':
				switch name[2] {
				case 's', 'S':
					switch name[3] {
					case 'e', 'E':
						return true // else
					}
				}
			}
		case 'f', 'F':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'o', 'O':
					switch name[3] {
					case 'm', 'M':
						return true // from
					}
				}
			case 'u', 'U':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'l', 'L':
						return true // full
					}
				}
			}
		case 'i', 'I':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'o', 'O':
						return true // into
					}
				}
			}
		case 'j', 'J':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'n', 'N':
						return true // join
					}
				}
			}
		case 'l', 'L':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'f', 'F':
					switch name[3] {
					case 't', 'T':
						return true // left
					}
				}
			case 'i', 'I':
				switch name[2] {
				case 'k', 'K':
					switch name[3] {
					case 'e', 'E':
						return true // like
					}
				}
			}
		case 'n', 'N':
			switch name[1] {
			case 'u', 'U':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'l', 'L':
						return true // null
					}
				}
			}
		case 'o', 'O':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'y', 'Y':
						return true // only
					}
				}
			}
		case 's', 'S':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'm', 'M':
					switch name[3] {
					case 'e', 'E':
						return true // some
					}
				}
			}
		case 't', 'T':
			switch name[1] {
			case 'h', 'H':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'n', 'N':
						return true // then
					}
				}
			case 'r', 'R':
				switch name[2] {
				case 'u', 'U':
					switch name[3] {
					case 'e', 'E':
						return true // true
					}
				}
			}
		case 'u', 'U':
			switch name[1] {
			case 's', 'S':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'r', 'R':
						return true // user
					}
				}
			}
		case 'w', 'W':
			switch name[1] {
			case 'h', 'H':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'n', 'N':
						return true // when
					}
				}
			case 'i', 'I':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'h', 'H':
						return true // with
					}
				}
			}
		}
	case 5:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'r', 'R':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 'y', 'Y':
							return true // array
						}
					}
				}
			}
		case 'c', 'C':
			switch name[1] {
			case 'h', 'H':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'c', 'C':
						switch name[4] {
						case 'k', 'K':
							return true // check
						}
					}
				}
			case 'r', 'R':
				switch name[2] {
				case 'o', 'O':
					switch name[3] {
					case 's', 'S':
						switch name[4] {
						case 's', 'S':
							return true // cross
						}
					}
				}
			}
		case 'f', 'F':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 's', 'S':
						switch name[4] {
						case 'e', 'E':
							return true // false
						}
					}
				}
			}
		case 'g', 'G':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'a', 'A':
					switch name[3] {
					case 'n', 'N':
						switch name[4] {
						case 't', 'T':
							return true // grant
						}
					}
				case 'o', 'O':
					switch name[3] {
					case 'u', 'U':
						switch name[4] {
						case 'p', 'P':
							return true // group
						}
					}
				}
			}
		case 'i', 'I':
			switch name[1] {
			case 'l', 'L':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'k', 'K':
						switch name[4] {
						case 'e', 'E':
							return true // ilike
						}
					}
				}
			case 'n', 'N':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							return true // inner
						}
					}
				}
			}
		case 'l', 'L':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 'm', 'M':
					switch name[3] {
					case 'i', 'I':
						switch name[4] {
						case 't', 'T':
							return true // limit
						}
					}
				}
			}
		case 'o', 'O':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'd', 'D':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							return true // order
						}
					}
				}
			case 'u', 'U':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							return true // outer
						}
					}
				}
			}
		case 'r', 'R':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 'g', 'G':
					switch name[3] {
					case 'h', 'H':
						switch name[4] {
						case 't', 'T':
							return true // right
						}
					}
				}
			}
		case 't', 'T':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 'b', 'B':
					switch name[3] {
					case 'l', 'L':
						switch name[4] {
						case 'e', 'E':
							return true // table
						}
					}
				}
			}
		case 'u', 'U':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'o', 'O':
						switch name[4] {
						case 'n', 'N':
							return true // union
						}
					}
				}
			case 's', 'S':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'n', 'N':
						switch name[4] {
						case 'g', 'G':
							return true // using
						}
					}
				}
			}
		case 'w', 'W':
			switch name[1] {
			case 'h', 'H':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'r', 'R':
						switch name[4] {
						case 'e', 'E':
							return true // where
						}
					}
				}
			}
		}
	case 6:
		switch name[0] {
		case 'b', 'B':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'y', 'Y':
								return true // binary
							}
						}
					}
				}
			}
		case 'c', 'C':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'u', 'U':
						switch name[4] {
						case 'm', 'M':
							switch name[5] {
							case 'n', 'N':
								return true // column
							}
						}
					}
				}
			case 'r', 'R':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 't', 'T':
							switch name[5] {
							case 'e', 'E':
								return true // create
							}
						}
					}
				}
			}
		case 'e', 'E':
			switch name[1] {
			case 'x', 'X':
				switch name[2] {
				case 'c', 'C':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'p', 'P':
							switch name[5] {
							case 't', 'T':
								return true // except
							}
						}
					}
				}
			}
		case 'f', 'F':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'z', 'Z':
							switch name[5] {
							case 'e', 'E':
								return true // freeze
							}
						}
					}
				}
			}
		case 'h', 'H':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 'v', 'V':
					switch name[3] {
					case 'i', 'I':
						switch name[4] {
						case 'n', 'N':
							switch name[5] {
							case 'g', 'G':
								return true // having
							}
						}
					}
				}
			}
		case 'i', 'I':
			switch name[1] {
			case 's', 'S':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 'u', 'U':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 'l', 'L':
								return true // isnull
							}
						}
					}
				}
			}
		case 'o', 'O':
			switch name[1] {
			case 'f', 'F':
				switch name[2] {
				case 'f', 'F':
					switch name[3] {
					case 's', 'S':
						switch name[4] {
						case 'e', 'E':
							switch name[5] {
							case 't', 'T':
								return true // offset
							}
						}
					}
				}
			}
		case 's', 'S':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'c', 'C':
							switch name[5] {
							case 't', 'T':
								return true // select
							}
						}
					}
				}
			}
		case 'u', 'U':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'q', 'Q':
						switch name[4] {
						case 'u', 'U':
							switch name[5] {
							case 'e', 'E':
								return true // unique
							}
						}
					}
				}
			}
		case 'w', 'W':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 'd', 'D':
						switch name[4] {
						case 'o', 'O':
							switch name[5] {
							case 'w', 'W':
								return true // window
							}
						}
					}
				}
			}
		}
	case 7:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'a', 'A':
					switch name[3] {
					case 'l', 'L':
						switch name[4] {
						case 'y', 'Y':
							switch name[5] {
							case 's', 'S':
								switch name[6] {
								case 'e', 'E':
									return true // analyse
								}
							case 'z', 'Z':
								switch name[6] {
								case 'e', 'E':
									return true // analyze
								}
							}
						}
					}
				}
			}
		case 'c', 'C':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'l', 'L':
					switch name[3] {
					case 'l', 'L':
						switch name[4] {
						case 'a', 'A':
							switch name[5] {
							case 't', 'T':
								switch name[6] {
								case 'e', 'E':
									return true // collate
								}
							}
						}
					}
				}
			}
		case 'd', 'D':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'f', 'F':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 'u', 'U':
							switch name[5] {
							case 'l', 'L':
								switch name[6] {
								case 't', 'T':
									return true // default
								}
							}
						}
					}
				}
			}
		case 'f', 'F':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'r', 'R':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'g', 'G':
								switch name[6] {
								case 'n', 'N':
									return true // foreign
								}
							}
						}
					}
				}
			}
		case 'l', 'L':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'a', 'A':
								switch name[6] {
								case 'l', 'L':
									return true // lateral
								}
							}
						}
					}
				}
			case 'e', 'E':
				switch name[2] {
				case 'a', 'A':
					switch name[3] {
					case 'd', 'D':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 'g', 'G':
									return true // leading
								}
							}
						}
					}
				}
			}
		case 'n', 'N':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'u', 'U':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'a', 'A':
								switch name[6] {
								case 'l', 'L':
									return true // natural
								}
							}
						}
					}
				}
			case 'o', 'O':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'n', 'N':
						switch name[4] {
						case 'u', 'U':
							switch name[5] {
							case 'l', 'L':
								switch name[6] {
								case 'l', 'L':
									return true // notnull
								}
							}
						}
					}
				}
			}
		case 'p', 'P':
			switch name[1] {
			case 'l', 'L':
				switch name[2] {
				case 'a', 'A':
					switch name[3] {
					case 'c', 'C':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 'g', 'G':
									return true // placing
								}
							}
						}
					}
				}
			case 'r', 'R':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 'm', 'M':
						switch name[4] {
						case 'a', 'A':
							switch name[5] {
							case 'r', 'R':
								switch name[6] {
								case 'y', 'Y':
									return true // primary
								}
							}
						}
					}
				}
			}
		case 's', 'S':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 'm', 'M':
					switch name[3] {
					case 'i', 'I':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 'a', 'A':
								switch name[6] {
								case 'r', 'R':
									return true // similar
								}
							}
						}
					}
				}
			}
		}
	case 8:
		switch name[0] {
		case 'd', 'D':
			switch name[1] {
			case 'i', 'I':
				switch name[2] {
				case 's', 'S':
					switch name[3] {
					case 't', 'T':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 'c', 'C':
									switch name[7] {
									case 't', 'T':
										return true // distinct
									}
								}
							}
						}
					}
				}
			}
		case 'o', 'O':
			switch name[1] {
			case 'v', 'V':
				switch name[2] {
				case 'e', 'E':
					switch name[3] {
					case 'r', 'R':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 'a', 'A':
								switch name[6] {
								case 'p', 'P':
									switch name[7] {
									case 's', 'S':
										return true // overlaps
									}
								}
							}
						}
					}
				}
			}
		case 't', 'T':
			switch name[1] {
			case 'r', 'R':
				switch name[2] {
				case 'a', 'A':
					switch name[3] {
					case 'i', 'I':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 'i', 'I':
								switch name[6] {
								case 'n', 'N':
									switch name[7] {
									case 'g', 'G':
										return true // trailing
									}
								}
							}
						}
					}
				}
			}
		case 'v', 'V':
			switch name[1] {
			case 'a', 'A':
				switch name[2] {
				case 'r', 'R':
					switch name[3] {
					case 'i', 'I':
						switch name[4] {
						case 'a', 'A':
							switch name[5] {
							case 'd', 'D':
								switch name[6] {
								case 'i', 'I':
									switch name[7] {
									case 'c', 'C':
										return true // variadic
									}
								}
							}
						}
					}
				}
			}
		}
	case 9:
		switch name[0] {
		case 'i', 'I':
			switch name[1] {
			case 'n', 'N':
				switch name[2] {
				case 'i', 'I':
					switch name[3] {
					case 't', 'T':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'a', 'A':
								switch name[6] {
								case 'l', 'L':
									switch name[7] {
									case 'l', 'L':
										switch name[8] {
										case 'y', 'Y':
											return true // initially
										}
									}
								}
							}
						}
					}
				case 't', 'T':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 's', 'S':
								switch name[6] {
								case 'e', 'E':
									switch name[7] {
									case 'c', 'C':
										switch name[8] {
										case 't', 'T':
											return true // intersect
										}
									}
								}
							}
						}
					}
				}
			}
		case 'l', 'L':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'c', 'C':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 't', 'T':
								switch name[6] {
								case 'i', 'I':
									switch name[7] {
									case 'm', 'M':
										switch name[8] {
										case 'e', 'E':
											return true // localtime
										}
									}
								}
							}
						}
					}
				}
			}
		case 'r', 'R':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'u', 'U':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 'i', 'I':
									switch name[7] {
									case 'n', 'N':
										switch name[8] {
										case 'g', 'G':
											return true // returning
										}
									}
								}
							}
						}
					}
				}
			}
		case 's', 'S':
			switch name[1] {
			case 'y', 'Y':
				switch name[2] {
				case 'm', 'M':
					switch name[3] {
					case 'm', 'M':
						switch name[4] {
						case 'e', 'E':
							switch name[5] {
							case 't', 'T':
								switch name[6] {
								case 'r', 'R':
									switch name[7] {
									case 'i', 'I':
										switch name[8] {
										case 'c', 'C':
											return true // symmetric
										}
									}
								}
							}
						}
					}
				}
			}
		}
	case 10:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 's', 'S':
				switch name[2] {
				case 'y', 'Y':
					switch name[3] {
					case 'm', 'M':
						switch name[4] {
						case 'm', 'M':
							switch name[5] {
							case 'e', 'E':
								switch name[6] {
								case 't', 'T':
									switch name[7] {
									case 'r', 'R':
										switch name[8] {
										case 'i', 'I':
											switch name[9] {
											case 'c', 'C':
												return true // asymmetric
											}
										}
									}
								}
							}
						}
					}
				}
			}
		case 'c', 'C':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 's', 'S':
						switch name[4] {
						case 't', 'T':
							switch name[5] {
							case 'r', 'R':
								switch name[6] {
								case 'a', 'A':
									switch name[7] {
									case 'i', 'I':
										switch name[8] {
										case 'n', 'N':
											switch name[9] {
											case 't', 'T':
												return true // constraint
											}
										}
									}
								}
							}
						}
					}
				}
			}
		case 'd', 'D':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'f', 'F':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'r', 'R':
								switch name[6] {
								case 'a', 'A':
									switch name[7] {
									case 'b', 'B':
										switch name[8] {
										case 'l', 'L':
											switch name[9] {
											case 'e', 'E':
												return true // deferrable
											}
										}
									}
								}
							}
						}
					}
				}
			}
		case 'r', 'R':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 'f', 'F':
					switch name[3] {
					case 'e', 'E':
						switch name[4] {
						case 'r', 'R':
							switch name[5] {
							case 'e', 'E':
								switch name[6] {
								case 'n', 'N':
									switch name[7] {
									case 'c', 'C':
										switch name[8] {
										case 'e', 'E':
											switch name[9] {
											case 's', 'S':
												return true // references
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	case 12:
		switch name[0] {
		case 'c', 'C':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'n', 'N':
					switch name[3] {
					case 'c', 'C':
						switch name[4] {
						case 'u', 'U':
							switch name[5] {
							case 'r', 'R':
								switch name[6] {
								case 'r', 'R':
									switch name[7] {
									case 'e', 'E':
										switch name[8] {
										case 'n', 'N':
											switch name[9] {
											case 't', 'T':
												switch name[10] {
												case 'l', 'L':
													switch name[11] {
													case 'y', 'Y':
														return true // concurrently
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			case 'u', 'U':
				switch name[2] {
				case 'r', 'R':
					switch name[3] {
					case 'r', 'R':
						switch name[4] {
						case 'e', 'E':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 't', 'T':
									switch name[7] {
									case '_':
										switch name[8] {
										case 'd', 'D':
											switch name[9] {
											case 'a', 'A':
												switch name[10] {
												case 't', 'T':
													switch name[11] {
													case 'e', 'E':
														return true // current_date
													}
												}
											}
										case 'r', 'R':
											switch name[9] {
											case 'o', 'O':
												switch name[10] {
												case 'l', 'L':
													switch name[11] {
													case 'e', 'E':
														return true // current_role
													}
												}
											}
										case 't', 'T':
											switch name[9] {
											case 'i', 'I':
												switch name[10] {
												case 'm', 'M':
													switch name[11] {
													case 'e', 'E':
														return true // current_time
													}
												}
											}
										case 'u', 'U':
											switch name[9] {
											case 's', 'S':
												switch name[10] {
												case 'e', 'E':
													switch name[11] {
													case 'r', 'R':
														return true // current_user
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		case 's', 'S':
			switch name[1] {
			case 'e', 'E':
				switch name[2] {
				case 's', 'S':
					switch name[3] {
					case 's', 'S':
						switch name[4] {
						case 'i', 'I':
							switch name[5] {
							case 'o', 'O':
								switch name[6] {
								case 'n', 'N':
									switch name[7] {
									case '_':
										switch name[8] {
										case 'u', 'U':
											switch name[9] {
											case 's', 'S':
												switch name[10] {
												case 'e', 'E':
													switch name[11] {
													case 'r', 'R':
														return true // session_user
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	case 13:
		switch name[0] {
		case 'a', 'A':
			switch name[1] {
			case 'u', 'U':
				switch name[2] {
				case 't', 'T':
					switch name[3] {
					case 'h', 'H':
						switch name[4] {
						case 'o', 'O':
							switch name[5] {
							case 'r', 'R':
								switch name[6] {
								case 'i', 'I':
									switch name[7] {
									case 'z', 'Z':
										switch name[8] {
										case 'a', 'A':
											switch name[9] {
											case 't', 'T':
												switch name[10] {
												case 'i', 'I':
													switch name[11] {
													case 'o', 'O':
														switch name[12] {
														case 'n', 'N':
															return true // authorization
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	case 14:
		switch name[0] {
		case 'l', 'L':
			switch name[1] {
			case 'o', 'O':
				switch name[2] {
				case 'c', 'C':
					switch name[3] {
					case 'a', 'A':
						switch name[4] {
						case 'l', 'L':
							switch name[5] {
							case 't', 'T':
								switch name[6] {
								case 'i', 'I':
									switch name[7] {
									case 'm', 'M':
										switch name[8] {
										case 'e', 'E':
											switch name[9] {
											case 's', 'S':
												switch name[10] {
												case 't', 'T':
													switch name[11] {
													case 'a', 'A':
														switch name[12] {
														case 'm', 'M':
															switch name[13] {
															case 'p', 'P':
																return true // localtimestamp
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	case 17:
		switch name[0] {
		case 'c', 'C':
			switch name[1] {
			case 'u', 'U':
				switch name[2] {
				case 'r', 'R':
					switch name[3] {
					case 'r', 'R':
						switch name[4] {
						case 'e', 'E':
							switch name[5] {
							case 'n', 'N':
								switch name[6] {
								case 't', 'T':
									switch name[7] {
									case '_':
										switch name[8] {
										case 't', 'T':
											switch name[9] {
											case 'i', 'I':
												switch name[10] {
												case 'm', 'M':
													switch name[11] {
													case 'e', 'E':
														switch name[12] {
														case 's', 'S':
															switch name[13] {
															case 't', 'T':
																switch name[14] {
																case 'a', 'A':
																	switch name[15] {
																	case 'm', 'M':
																		switch name[16] {
																		case 'p', 'P':
																			return true // current_timestamp
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return false
}
